Xyphyn/photon

- src/lib/components/input/MultiSelect.svelte
- src/routes/+page.svelte
I thought the style of the MultiSelect wasn't really fitting the style of the interface. Let me know what you think.
> Update MultiSelect style

- src/lib/components/lemmy/comment/Comments.svelte
possibly a bug? wasn't recorded in the readme.
> fix 0.18.3 comment loading being different

- src/lib/components/ui/Avatar.svelte
- src/lib/components/ui/Sidebar.svelte
This will allow users to hover over the avatars in a collapsed sidebar and see the name of the community.
> misc: add title attribute to Avatar

- src/lib/components/lemmy/post/Post.svelte
> Revert "Rearrange post meta for better alignment in compact post view"

- README.md
- src/lib/settings.ts
- src/lib/ui/colors.ts
PR to add support for features requested in issue #108
I wasn't clear on what "newComments" setting does, if anything, so I didn't add a variable import for that.
I also did not implement env var settings for the `notifications` options as those may or may not be implemented.
> Updated settings.ts and README

- src/lib/components/lemmy/post/Post.svelte
> Set PostActions div mt-2 not only for list view

- README.md
Hopefully it will be useful to someone
> Added photon.zhenyapav.com as a public instance

- README.md
Added my photon instance to the public instances list
> Add ph.buckodr.ink to instances list

- README.md
I added my instance and also added `mailto:` to the email addresses
> Add phtn.ngn.tf to the instance list

- README.md
I hope someone find this useful
> Add p.darrennathanael.com instance

- package.json
- src/lib/auth.ts
- src/lib/components/lemmy/comment/CommentVote.svelte
- src/lib/components/lemmy/comment/Comments.svelte
- src/lib/components/lemmy/post/Post.svelte
- src/lib/components/lemmy/post/PostMeta.svelte
- src/lib/components/lemmy/post/PostVote.svelte
- src/lib/components/lemmy/util/SearchBar.svelte
- src/lib/components/markdown/Markdown.svelte
- src/lib/components/ui/StickyCard.svelte
- src/lib/components/ui/layout/Shell.svelte
- src/lib/components/ui/navbar/NavButton.svelte
- src/lib/components/ui/navbar/Navbar.svelte
- src/lib/components/ui/navbar/Profile.svelte
- src/lib/components/ui/sidebar/ProfileButton.svelte
- src/lib/components/ui/sidebar/Sidebar.svelte
- src/lib/components/ui/sidebar/SidebarButton.svelte
- src/lib/components/util/FormattedNumber.svelte
- src/lib/lemmy/item.ts
- src/lib/settings.ts
- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/accounts/+page.svelte
- src/routes/c/[name]/+page.svelte
- src/routes/post/[instance]/[id=integer]/+page.svelte
- src/routes/settings/+page.svelte
- tailwind.config.js
for those who want the old navigation, go to settings
> feat: redesign navigation

- src/routes/admin/applications/Application.svelte
Fixes #330.
I dived into the source code, and it just happened that at the same time someone filed the lowest hanging fruit ever.
> Remove unnecessary curly bracket

- src/lib/components/lemmy/post/Post.svelte
- src/lib/components/lemmy/post/PostLink.svelte
- src/lib/components/lemmy/post/PostMeta.svelte
- src/lib/components/lemmy/post/media/PostIframe.svelte
- src/lib/components/lemmy/post/media/PostMedia.svelte
- src/lib/components/lemmy/post/media/PostMediaCompact.svelte
This is comments / documentation only, no actual code has been changed.
As a new contributor it was somewhat tedious to figure out what the components do. Their purposes and relationships aren't always straightforward. Often the same component is responsible for multiple distinct jobs. I added a couple [@component-annotated](https://svelte.dev/docs/faq#how-do-i-document-my-components) doc comments on things that weren't immediately obvious to me.
Maybe some of the quirks could be refactored out, too.
> docs: Post component comments

- src/lib/components/lemmy/community/CommunityCard.svelte
- src/lib/components/lemmy/community/CommunityHeader.svelte
- src/lib/components/ui/Expandable.svelte
- src/lib/components/ui/layout/pages/Header.svelte
- src/lib/components/ui/layout/pages/Tabs.svelte
- src/lib/i18n/en.json
- src/routes/c/[name]/+page.svelte
- src/routes/profile/(local_user)/blocks/+page.svelte
- src/routes/profile/(local_user)/settings/+page.svelte
- src/routes/profile/+layout.svelte
- src/routes/profile/+layout.ts
- src/routes/profile/+page.svelte
- src/routes/profile/+page.ts
- src/routes/profile/user/+page.svelte
- src/routes/settings/+page.svelte
- src/routes/settings/Section.svelte
- src/routes/u/[name]/+page.svelte
added an "account" section in settings that just links to profile, settings sections are collapsible, some wording was changed, and the profile button will take you to an instant overview rather than loading all your posts.
> design: reorganize profile

- src/routes/admin/applications/+page.svelte
- src/routes/admin/applications/+page.ts
- src/routes/admin/applications/Application.svelte
- src/routes/admin/team/+page.svelte
Fixes constant refreshes as well
> cleanup: tweak some designs in admin

- src/routes/admin/config/+page.svelte
> Fix: Admin NSFW toggle

- package.json
- src/lib/components/lemmy/comment/CommentListVirtualizer.svelte
- src/lib/components/lemmy/post/feed/VirtualFeed.svelte
- src/lib/components/render/VirtualList.svelte
- src/lib/i18n/en.json
- src/lib/lemmy/postfeed.svelte.ts
- src/routes/post/[instance]/[id=integer]/+page.svelte
- src/routes/post/[instance]/[id=integer]/CommentProvider.svelte
With a custom virtualizer I can remove unnecessary functions, reduce bundle size, optimize it for my use case, and debug easier.
> v2: replace @tanstack/svelte-virtual with custom virtualizer

- src/routes/inbox/+page.svelte
> fix: Inbox shows outgoing messages

- src/routes/inbox/InboxItem.svelte
I now realize that I filed multiple issues in one. This fixes half of #528.
**Changes:**
- Inbox jump button is now also present for messages and links to the chat.
> feat: Inbox jump to chat button

- src/lib/components/lemmy/user/UserAutocomplete.svelte
- src/routes/inbox/messages/+page.svelte
Closes #576 
**Changes:**
- "New chat" modal filters out logged in account.
> fix: inbox/messages/ new chat self-select

- src/lib/components/markdown/renderers/MdLink.svelte
> Fix: external link on comment should open in new tab

- src/lib/components/markdown/renderers/MdLink.svelte
> Revert "Fix: external link on comment should open in new tab"
