Xyphyn/photon

.github/workflows/docker-image.yml
This will push a docker build to the Github container registry every time a tagged release is made. You do not need to do any configuration for this, it will "just" work right out of the box like this. You may need to change the package visibility settings in the repository setting to "public" once the first version has been pushed. 
Thanks for your hard work!
=> Add automatic docker builds

src/lib/components/input/TextInput.svelte, src/routes/communities/+page.svelte
This allows the user to simply enter in their filter and press enter, rather than having to press the "Search" button.
=> fix: add onchange for Communities TextInput

src/lib/settings.ts
UI settings were being overwritten on refresh. Changing this check appears to resolve this issue and allows for the UI settings to persist.
=> fix: allow UI settings to persist

src/routes/post/[instance]/[id]/+page.svelte
Right now, if a post does not have a post.thumbnail_url and is just a link to another website, the link is not displayed... so the user cannot go to the actual article.
This copies the link code from the Post object and provides a link if there is a post.url but not a post.thumbnail_url.
An example of this is here:
https://nu.lemdro.id/post/lemmy.world/2164687
There is no thumbnail, so there is no link for the user to click on to visit the article.
=> fix: show post.url if the post does not have a thumbnail

src/lib/components/lemmy/post/PostForm.svelte
Right now, listing and searching 'All' communities makes it difficult to find the appropriate community to post to, particularly if it has a common name such as technology, news, or linux.
Downside of this is that you can only post to communities you subscribe to... but this was what we did before 9c9a3dc.
=> fix: only list/search subscribed communities

src/lib/components/lemmy/post/PostForm.svelte
Currently posts creation omits the URL if it is not an image upload.
=> fix: include post url if it is not an image upload

src/routes/post/[instance]/[id]/+page.svelte
Need to set type_ to 'All' when calling getComments().  Otherwise, trying sort the comments on a post by "Top" or "New" will refresh without any comments.
=> fix: properly load comments when sorting

Dockerfile
The official node image has a user already built-in expressly for this purpose.
=> Use unprivileged "node" user in Dockerfile

src/lib/components/lemmy/SiteCard.svelte, src/lib/components/lemmy/comment/Comment.svelte, src/lib/components/lemmy/comment/CommentItem.svelte, src/lib/components/lemmy/community/CommunityCard.svelte, src/lib/components/lemmy/post/Post.svelte, src/routes/post/[instance]/[id]/+page.svelte, src/routes/u/[name]/+page.svelte
Here is the same lemmy post shown by lemmy-ui and by photon:
- [lemmy-ui](https://lemmy.ndlug.org/post/1612)
- [photon](https://photon.ndlug.org/post/lemmy.ndlug.org/1612)
Depending on your local timezone, the relative time since the post will display differently for the two frontends. At the time of writing, lemmy-ui shows me "8 hours ago" (correct) while photon shows me "4h ago" (incorrect). I made the post myself around 12:38 EDT, which is 8 hours ago. Photon is off by 4 hours because my local time is UTC-04:00.
For posts, comments, and other objects, the `published` attribute is a string containing an ISO 8601 timestamp. This timestamp is UTC, though it is not explicit in the string's contents. When the `Date` constructor is used on such strings, they are parsed as though they are …
=> fix: parse date strings as UTC

src/lib/components/lemmy/comment/Comments.svelte, src/lib/components/lemmy/comment/comments.ts
As we build the map of nodes, keep track of the minimum depth level. Afterwards, nodes at the minimum depth level go into the tree as the roots.
We no longer need to check if the tree belongs to a parent comment or not.
Fixes #36 more.
=> fix: improve building comment tree

src/lib/components/util/RelativeDate.svelte
Relative datetimes (e.g. "42m ago") are displayed for posts, comments, user pages, community cards, and site cards. This patch wraps these relative datetimes in a `<time>` tag which has a `title` attribute and an ISO 8601 `datetime` attribute. The `title` allows users to see a full, non-relative timestamp when hovering with the mouse.
This is a feature that Reddit, tildes.net, and lemmy-ui have.
=> feat: hover on relative datetimes

src/lib/components/lemmy/comment/Comment.svelte
I often find myself resizing the textarea when replying to comments, so I was wondering if we can allow the replies textarea to use the full width just like the comment box at the top of the post.
Here is a screenshot demonstrating the difference (top is current, bottom is with change):
=> misc: allow replies to use max width (instead of small)

src/lib/components/ui/Navbar.svelte
Though the width and height attributes are set to 32 in this component, the height is overridden by the more general styling for `<img>` tags, which sets image heights to `auto`. For users with non-square avatars, their avatar may overflow beyond its ring border. Specify the `aspect-square` class to force a 1:1 aspect ratio. The Avatar component used for posts, comments, etc. already does this.
---
Before:
After:
=> fix: force navbar avatar to be square

src/lib/components/input/TextInput.svelte
Currently, when the INSTANCE_URL is set, the login with the INSTANCE_URL is unreadable in light mode:
With this change, we set different background colors for dark and light mode.  Here is the new light mode:
and new dark mode:
=> misc: set different disabled backgrounds for light and dark mode

src/lib/components/lemmy/comment/CommentActions.svelte
~This adds a link button to each comment so that users can link directly to a comment.  It uses the existing single thread view mechanism to display the single command (and its children).~
This adds a comment link action to each comment action menu so that users can link directly to a comment.  It uses the existing single thread view mechanism to display the single command (and its children).
=> feat: copy link action for comments

src/lib/components/lemmy/post/Post.svelte
When using the compact posts option, the thumbnail makes the text for the post meta wrap, which pushes the post title down and makes the post look misaligned. This change rearranges the post meta so that it span the width of the post and aligns the thumbnail with the post title.
Before:
After:
=> Rearrange post meta for better alignment in compact post view

src/lib/components/ui/sidebar/Sidebar.svelte, src/lib/settings.ts
Add an expandSidebar setting to remember if the sidebar is expanded or collapsed.  This allows the user to refresh or open a post in a new tab and keep the same sidebar state (rather than it always being expanded).
One possible quirk is that if a user has it collapsed in one tab, but expanded in another, it will remember which ever state was set last (most recently).  However, changing the state in one tab will not impact another (until a refresh occurs).
Fix #68
=> feat: store sidebar expanded state in settings

src/lib/components/ui/sidebar/CommunityList.svelte
If a community name is long and uses multiple lines, the avatar will shrink, leading to awkward alignment.
This adds a non-flexible container around the avatar to prevent this.
Before:
After:
=> misc: don't let community avatars on sidebar shrink

src/lib/settings.ts, src/routes/+page.svelte, src/routes/c/[name]/+page.svelte, src/routes/settings/+page.svelte
Add hidePosts.{deleted,removed} settings to control whether or not to display posts that have been marked as deleted or removed.  By default, these are enabled (ie. hidden) to correspond to Lemmy-UI behavior.
Currently, this change only hides these posts for the front page and community pages.
Before these settings are introduced, you can see all posts regardless of if they are deleted or removed:
After these changes, you can hide both removed and deleted:
Or just hide deleted:
Or just hide the removed:
=> feat: add ability to hide deleted or removed posts

src/lib/components/ui/StickyCard.svelte
Right now, the community card model displays the information in a very narrow column with a lot of extra whitespace on the side and a weird left border.  Likewise, user pages also include a left border if the StickyCard is placed at the top.
This removes the left border completely, and allows the StickyCard to be wider in order to allow for more information to be displayed.
Here is what a community sidebar looks like now:
After this change, the sidebar is wider and has no left border:
User profiles exhibit the same change at full screen.
Here is what the community modal looks like now:
As you can see, it is narrow and has a left border.  After this change, this is what the community modal looks like:
Likewise, here is what a user profile looks like if there is no sidebar:
Again, there is …
=> misc: allow community card to be full width and remove left border

README.md
Just noticed I had a typo in README.md with the wrong env var name for PUBLIC_SHOW_INSTANCES_COMMENTS.  I accidentally left off the "S" at the end.
=> Fixed incorrect env var name for showing instances for comments

src/lib/components/lemmy/moderation/CommentModerationMenu.svelte, src/lib/components/lemmy/moderation/ModerationMenu.svelte
This PR removes the check for whether a community is local before showing moderation options to instance admins.
In the main Lemmy UI, instance admins have full moderation control over remote content as far as their instance is concerned.  They can lock, unlock, remove content, community-ban a user, and pin posts to their local copy of the community.  While these only affect the local instance, they are important moderation abilities.
This allows instance admins to respond to reports from users of their instance when the reported content is from a federated instance (spam, NSFW, local instance rule violation, etc).  This is especially helpful when the remote admin/moderator is slow to respond to reports or if the content violates a local server rule but doesn't violate a rule on the …
=> Allow instance admins access to the "Moderation" menu for federated posts/comments

src/lib/components/lemmy/moderation/CommentModerationMenu.svelte, src/lib/components/lemmy/moderation/ModerationMenu.svelte, src/lib/components/lemmy/moderation/RemoveModal.svelte
Enhancement to the last [pull request](https://github.com/Xyphyn/photon/pull/122) with the following changes to better account for federated moderation:
It doesn't make sense to "Reply with reason" when removing a federated post/comment only on your instance (reported by Cole in the Matrix/Discord chat).  This PR updates `RemoveModal.svelte` to check whether you are a mod of the remote community or if the content is local to the instance to conditionally hide the "Reply with reason" options.
Additionally, the last PR (122) did not account for cross-instance community moderators before adding "(Instance Only)" to the Moderation and User headings in the moderation menus.  This covers the case where you are a local admin and also a moderator of a remote community so that it correctly …
=> Update Mod Menus to account for federated moderators - Hide 'reply with reason' if mod action is instance-only.

src/lib/components/markdown/Markdown.svelte
Adding a max width to markdown paragraphs improves readability on large screens, as it prevents long runs of text from taking the full width of the browser window.
Before:
After:
=> Add max-width to markdown paragraphs

src/lib/components/lemmy/post/Post.svelte, src/lib/components/ui/ExpandableImage.svelte
This PR attempts to center the images in the card view, which (IMO) looks better.
Before:
After:
=> Center images in card view

src/lib/components/lemmy/post/Post.svelte
This just centers the images again since it was gone after the new "cozy" layout was implemented.
I also scaled the images based on a max height, which looks good to me but please let me know what you think!
=> Center images and set max height

src/routes/modlog/item/ModlogItemTable.svelte
Show "Hidden" instead of leaving the mod name empty.
I think if the backend does not return the mod name, that means that they set it to be hidden so imo it's nice to explicitly show that to the user.
=> Show "hidden" for missing mod names in modlog

src/lib/components/lemmy/post/Post.svelte
I noticed that some posts in card view were showing a blank thumbnail, and in those cases the thumbnail URL was `undefined?format=webp&thumbnail=512`. This happens because the variable `post.post.thumbnail_url` was inside single quotation marks, so it was being interpreted as the literal string `post.post.thumbnail_url` instead of that variable's value, and so the thumbnail was being shown even if the variable was undefined.
=> Remove misplaced single quotation marks to avoid showing an undefined thumbnail in card view

README.md
This adds my instance of Photon, photon.thesanewriter.com, to the instance list. Though it defaults to my Lemmy instance for displaying posts, it can be changed to any other instance and be used generally.
=> Add thesanewriter instance to instance list

src/routes/admin/applications/Application.svelte
As an instance admin, this info is nice to have, and I sometimes open the official UI just to see it.
The placement is naturally up for debate, I'm unsure where it fits best.
In the (near) future, I'd also like to add a notification dot similar to inbox unreads, but for applications instead.
=> Add timestamp to registration applications

src/lib/lemmy.ts, src/routes/login/+page.svelte
Some minor UX suggestions, following the 'less is more' motto.
Before:
After:
- Only warn about the minimum instance version if there may be a compatibility issue
- Remove username placeholder because it's not communicating new information
- Remove subtitle to improve signal-to-noise ratio
I'm also playing with the idea of hiding the 2FA code field unless the Lemmy server signals that the account is protected with 2FA, but I've kept that out of scope for now.
=> Simplify login screen

src/lib/components/ui/sidebar/Sidebar.svelte, src/routes/accounts/+page.svelte
In the use case of https://photon.lemmy.world/, it might not make a lot of sense to display this:
I've hidden this sidebar link:
Hopefully this'll encourage anonymous visitors to explore and get involved.
=> A few UX tweaks

src/lib/components/lemmy/community/CommunityCard.svelte, src/lib/components/ui/sidebar/Sidebar.svelte
When you click the community avatar or title in the right sidebar, you'll be taken to the community's overview page. I've not made the `!memes@lemmy.ml` subtitle clickable because I assumed some users might want to copy and paste the reference.
=> Make community cards clickable

src/lib/components/lemmy/ObjectAutocomplete.svelte
Quick fix for #201 
Only shows lemmy instances in the instance autocomplete. Seems easier than letting it fail and showing a user friendly error message, since there are a LOT of non-Lemmy peers in most instances' federation lists.
=> Only show lemmy servers in instance autocomplete

src/routes/admin/applications/Application.svelte
Steps to reproduce Bug:
- Start Denial Process
- Enter any deny reason
- cancel Denial
- approve request instead
Result: Approved Application has displayed deny reason.
This fixes that by clearing the denyReason var before cancelling out of the review function
=> BugFix: Deny Reason does not get cleared

src/lib/components/lemmy/post/Post.svelte, src/lib/components/lemmy/post/media/PostMediaCompact.svelte
Related issues: #332 #323
Compact mode has been near useless to me since it doesn't display thumbnails for links. This pr adds just that, and a bit more.
This should only affect behaviour of compact view.
- Embed thumbnails are now shown, with a link icon in the corner
- Video thumbnails are now shown, with a camera icon in the corner
- Self-posts get a placeholder thumbnail, with a text document icon
- Thumbnail-less links get a placeholder thumbnail, with a link icon
- As a happy accidental side effect, this fixes a minor bug when expanding images are disabled: 
Images would expand before loading the post. The expanded image would then show up when going back one page.
The reasoning for the placeholders is from the left align issue. I'm not 100% sure what's the best approach for list …
=> Compact mode thumbnails

src/lib/components/lemmy/post/media/PostMediaCompact.svelte
Fixes small oversight in #340.
Not all videos have a thumbnail, this adds a placeholder.
=> video placeholder thumbnail

src/lib/components/lemmy/post/PostMeta.svelte
Before:
After:
I added a placeholder zero-height div to occupy the unused grid slot.
=> Remove empty space left by hideTitle

src/lib/components/ui/Avatar.svelte
I came across a community with an unreasonably long name. The name doesn't fit, and squishes the icon.
This is also possible on sitecard, and probably some other places.
Adding `flex-shrink-0` stops it:
Edit: Closes #345
=> Stop avatar squish

src/lib/components/lemmy/post/PostLink.svelte
Before:
After:
Related issues: #342
Proposal for better thumbnails on mobile.
Changes:
- New vertical layout created: Thumbnail is placed above the text on narrow screens.
- Old horizontal layout changed: thumbnail width is now consistent.
=> Vertical postlink layout for mobile

src/lib/components/lemmy/post/feed/VirtualFeed.svelte
Closes #342 again.
The culprit was this box.
One unit is 4px, making w-96 is too much for 360px screens.
Changes:
- Added width limit
=> fix: infinite scroll too wide for mobile

src/lib/components/lemmy/post/media/PostIframe.svelte
Related to #366.
This was pretty dumb on my part: The video shows up so I somehow didn't realize I should try if it actually plays.
<details>
</details>
Now the iframe gets a video id and works.
<details>
</details>
=> fix: m.youtube.com embeds

src/routes/accounts/+page.svelte, src/routes/login/+page.svelte
Related issues: #328
This hides guest login / logout buttons if photon is linked to an instance. Adding guests doesn't work with linked instances, which made guest logout especially infuriating since the only way I could get the guest user back was by removing logged in accounts.
<details>
<summary> Before </summary>
</details>
<details>
<summary> After </summary>
</details>
=> fix: hide guest actions in locked instance mode

src/lib/components/lemmy/post/helpers.ts, src/lib/components/lemmy/post/media/PostIframe.svelte
(https://lemmy.world/post/17853161)
Related issues: #367 
Changes:
- Recognize `/live/` urls in youtube regex. YT livestreams are now embedded.
=> feat: youtube livestream iframe

src/lib/components/lemmy/post/feed/VirtualFeed.svelte, src/lib/components/ui/EndPlaceholder.svelte, src/lib/i18n/en.json
Second attempt at #369 
Still needs to use translations, maybe rephrase it too.
I omitted the scroll to top button as it did not work.
=> feat: feed end indicator (2)

src/lib/components/lemmy/post/PostActions.svelte
Minor CSS changes to PostActions:
**Before:**
- The community name is long and wraps to multiple lines.
- The icon has shrunk under the weight of this community name.
**After:**
All of these fields overflow like this now.
- Overflow-ellipsis, nowrap for the text
- Icons don't shrink
=> PostActions fix overflow and wrap

src/routes/post/[instance]/[id=integer]/+page.svelte
Related issues: #406
The pencil icon for edited posts didn't show up in full post view. Fixed.
=> fix: post page has no edit icon

src/lib/components/ui/layout/Shell.svelte, src/lib/components/ui/layout/pages/Header.svelte, src/lib/components/ui/navbar/NavButton.svelte, src/lib/components/ui/navbar/Navbar.svelte, src/lib/i18n/en.json, src/lib/mono/button/Button.svelte, src/lib/settings.svelte.ts, src/routes/admin/+layout.svelte, src/routes/c/[name]/settings/+layout.svelte, src/routes/communities/+page.svelte, src/routes/inbox/+page.svelte, src/routes/post/[instance]/[id=integer]/+page.svelte, src/routes/profile/+layout.svelte, src/routes/saved/+page.svelte, src/routes/search/+page.svelte, src/routes/settings/+page.svelte, src/routes/util/+layout.svelte
This navbar is more efficient and lighter everywhere, and reduces shift. The only downside is that the customization for panel position was removed.
=> cleanup: switch to a css-based navbar

src/lib/lemmy.svelte.ts
This fixes the https://github.com/Xyphyn/photon/issues/508 by ignoring cache when a auth jwt is provided.
This allows the guest user to still use cache and authenticated user to have fresh data.
=> fix: /site caching for svelte-5

src/routes/inbox/messages/+page.svelte
Closes #441 
**Changes:**
- Message list now checks both _creator_ and _recipient_ to determine the other party, instead of just _creator._
- Message list shows the username of last sender.
=> fix: /inbox/messages: show chats without response

src/lib/components/markdown/renderers/MdQuote.svelte
Closes #532 
**Changes:**
- Blockquote now has the same flex & gap rules as the root markdown container div
Before / After:
=> fix: markdown blockquote paragraph gap
